name: Build MHI Industrial Nativo
on: [push]

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout Código
        uses: actions/checkout@v4

      - name: Configurar .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Publicar Aplicação (Self-Contained)
        # O self-contained garante que o programa abra em qualquer Windows
        run: dotnet publish -c Release -r win-x64 --self-contained true /p:PublishSingleFile=true /p:PublishReadyToRun=true -o publish_folder

      - name: Verificar Executável
        shell: powershell
        run: |
          $exe = Get-ChildItem -Path "publish_folder" -Filter "ManutencaoMHI.exe" -Recurse | Select-Object -First 1
          if ($exe) {
              Move-Item $exe.FullName "publish_folder\ManutencaoMHI.exe" -Force
          } else {
              throw "ERRO: ManutencaoMHI.exe não encontrado!"
          }

      - name: Criar Instalador (Inno Setup)
        shell: powershell
        run: |
          $iss = @"
          [Setup]
          AppName=Manutencao MHI Pro
          AppVersion=2.0
          DefaultDirName={autopf}\ManutencaoMHI
          OutputDir=installer_dist
          OutputBaseFilename=Instalador_MHI_Pro
          Compression=lzma
          SolidCompression=yes
          PrivilegesRequired=admin

          [Tasks]
          Name: "desktopicon"; Description: "Criar atalho na Área de Trabalho"

          [Files]
          Source: "publish_folder\ManutencaoMHI.exe"; DestDir: "{app}"; Flags: ignoreversion

          [Icons]
          Name: "{autodesktop}\Manutencao MHI Pro"; Filename: "{app}\ManutencaoMHI.exe"; Tasks: desktopicon
          Name: "{group}\Manutencao MHI Pro"; Filename: "{app}\Manutencao_MHI.exe"

          [Run]
          Filename: "{app}\ManutencaoMHI.exe"; Description: "Lançar Sistema"; Flags: nowait postinstall
          "@
          $iss | Out-File -FilePath setup.iss -Encoding utf8
          iscc setup.iss

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: Instalador-Final
          path: installer_dist/Instalador_MHI_Pro.exe
